version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8000"
    depends_on:
      - dynamodb
    env_file:
      - ./backend/.env

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  dynamodb_data:
